//
//  HowWorkModels.swift
//  Devlight
//
//  Created by Anderson Oliveira on 09/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct Work {
    let image: String
    let title: String
    
    static let mockedWork: [Work] = [
        Work(image: "chess", title: "Strategy"),
        Work(image: "compass", title: "Desing"),
        Work(image: "debug", title: "Development"),
        Work(image: "setting", title: "Quality Assurance")
    ]
}

struct HowWorkScene {

}
