//
//  HowWorkInteractor.swift
//  Devlight
//
//  Created by Anderson Oliveira on 09/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol HowWorkInteractorInput {
    
}

protocol HowWorkInteractorOutput {
    
}

protocol HowWorkDataSource {
    
}

protocol HowWorkDataDestination {
    
}

class HowWorkInteractor: HowWorkInteractorInput, HowWorkDataSource, HowWorkDataDestination {
    
    var output: HowWorkInteractorOutput?
    
    // MARK: Business logic
    

}
