//
//  HowWorkRouter.swift
//  Devlight
//
//  Created by Anderson Oliveira on 09/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol HowWorkRouterInput {
    
}

protocol HowWorkRouterDataSource: class {
    
}

protocol HowWorkRouterDataDestination: class {
    
}

class HowWorkRouter: HowWorkRouterInput {
    
    weak var viewController: HowWorkViewController!
    weak private var dataSource: HowWorkRouterDataSource!
    weak var dataDestination: HowWorkRouterDataDestination!
    
    init(viewController: HowWorkViewController, dataSource: HowWorkRouterDataSource, dataDestination: HowWorkRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
