//
//  HowWorkViewController.swift
//  Devlight
//
//  Created by Anderson Oliveira on 09/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol HowWorkViewControllerInput {
    
}

protocol HowWorkViewControllerOutput {
    
}

class HowWorkViewController: UIViewController, HowWorkViewControllerInput {
    
    // MARK: IBOutlets
    
    @IBOutlet weak var collectionView: UICollectionView!
    
    // MARK: Properties
    
    var output: HowWorkViewControllerOutput?
    var router: HowWorkRouter?
    let collectionViewCellHeightCoefficient: CGFloat = 0.5
    let collectionViewCellWidthCoefficient: CGFloat = 0.6
    let mockedWork: [Work] = Work.mockedWork

    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        HowWorkConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupCollectionView()
        registerCells()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        collectionView.reloadData()
    }
    
    // MARK: Requests
    
    
    // MARK: Display logic
    
}

extension HowWorkViewController {

    private func setupCollectionView() {
        let collectionViewSize = CGSize(width: collectionView.frame.width * collectionViewCellWidthCoefficient,
                                        height: collectionView.frame.height * collectionViewCellHeightCoefficient)
        let gravitySliderLayout = GravitySliderFlowLayout(with: collectionViewSize,
                                                          scrollDirection: .horizontal)
        collectionView.collectionViewLayout = gravitySliderLayout
        collectionView.backgroundColor = .clear
    }

    private func registerCells() {
        let cellNib = UINib(nibName: HowWorkCollectionViewCell.cellIdentifier, bundle: nil)
        collectionView.register(cellNib, forCellWithReuseIdentifier: HowWorkCollectionViewCell.cellIdentifier)
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension HowWorkViewController: HowWorkPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
