//
//  WorkWithConfigurator.swift
//  Devlight
//
//  Created by Anderson Oliveira on 09/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension WorkWithInteractor: WorkWithViewControllerOutput, WorkWithRouterDataSource, WorkWithRouterDataDestination {
}

extension WorkWithPresenter: WorkWithInteractorOutput {
}

class WorkWithConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = WorkWithConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: WorkWithViewController) {
        
        let presenter = WorkWithPresenter()
        presenter.output = viewController
        
        let interactor = WorkWithInteractor()
        interactor.output = presenter
        
        let router = WorkWithRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
