//
//  WorkWithInteractor.swift
//  Devlight
//
//  Created by Anderson Oliveira on 09/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol WorkWithInteractorInput {
    
}

protocol WorkWithInteractorOutput {
    
}

protocol WorkWithDataSource {
    
}

protocol WorkWithDataDestination {
    
}

class WorkWithInteractor: WorkWithInteractorInput, WorkWithDataSource, WorkWithDataDestination {
    
    var output: WorkWithInteractorOutput?
    
    // MARK: Business logic
    

}
