//
//  WorkWithModels.swift
//  Devlight
//
//  Created by Anderson Oliveira on 09/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct WorkServices {
    let works: [Work]

    static let mockedWorkServices: [WorkServices] = [
        WorkServices(works: [
            Work(image: "truck", title: "Delivery"),
            Work(image: "ecommerce", title: "E-commerce"),
            Work(image: "grafic", title: "Fintech"),
            Work(image: "users", title: "Social Network")
        ]),
        WorkServices(works: [
            Work(image: "truck", title: "Delivery"),
            Work(image: "ecommerce", title: "E-commerce"),
            Work(image: "grafic", title: "Fintech"),
            Work(image: "users", title: "Social Network")
        ]),
        WorkServices(works: [
            Work(image: "truck", title: "Delivery"),
            Work(image: "ecommerce", title: "E-commerce"),
            Work(image: "grafic", title: "Fintech"),
            Work(image: "users", title: "Social Network")
        ]),
    ]
}

struct WorkWithScene {
    
}
