//
//  WorkWithRouter.swift
//  Devlight
//
//  Created by Anderson Oliveira on 09/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol WorkWithRouterInput {
    
}

protocol WorkWithRouterDataSource: class {
    
}

protocol WorkWithRouterDataDestination: class {
    
}

class WorkWithRouter: WorkWithRouterInput {
    
    weak var viewController: WorkWithViewController!
    weak private var dataSource: WorkWithRouterDataSource!
    weak var dataDestination: WorkWithRouterDataDestination!
    
    init(viewController: WorkWithViewController, dataSource: WorkWithRouterDataSource, dataDestination: WorkWithRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
