//
//  PortfolioModels.swift
//  Devlight
//
//  Created by Anderson Oliveira on 08/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

import Foundation
import UIKit

struct Coordinates {
    let startPoint: CGPoint
    let endPoint: CGPoint
}

enum Direction {
    case topToBottom
    case leftToRight
    
    var coordinates: Coordinates {
        switch self {
        case .topToBottom:
            return Coordinates(startPoint: CGPoint(x: 0.5, y: 0.0), endPoint: CGPoint(x: 0.5, y: 1.0))
        case .leftToRight:
            return Coordinates(startPoint: CGPoint(x: 0.0, y: 0.5), endPoint: CGPoint(x: 1.0, y: 0.5))
        }
    }
}

enum PortfolioItem: CaseIterable {
    case howWork
    case workWith
}

struct PortfolioScene {
    
}
