//
//  PortfolioViewController.swift
//  Devlight
//
//  Created by Anderson Oliveira on 08/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol PortfolioViewControllerInput {
    
}

protocol PortfolioViewControllerOutput {
    
}

struct Coordinates {
    let startPoint: CGPoint
    let endPoint: CGPoint
}

enum Direction {
    case topToBottom
    case leftToRight

    var coordinates: Coordinates {
        switch self {
        case .topToBottom:
            return Coordinates(startPoint: CGPoint(x: 0.5, y: 0.0), endPoint: CGPoint(x: 0.5, y: 1.0))
        case .leftToRight:
            return Coordinates(startPoint: CGPoint(x: 0.0, y: 0.5), endPoint: CGPoint(x: 1.0, y: 0.5))
        }
    }
}

class PortfolioViewController: UIViewController, PortfolioViewControllerInput {

    // mARK: IBOutlets

    @IBOutlet weak var headerView: UIView!

    // MARK: Properties

    var output: PortfolioViewControllerOutput?
    var router: PortfolioRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        PortfolioConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupStyle()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        setupGradient(view: headerView,
                      direction: .topToBottom,
                      colors: [.white, UIColor.white.withAlphaComponent(0.0)],
                      locations: [0.85, 1.0])
        setupGradient(view: view, direction: .topToBottom, colors: [.white, UIColor.veryLightGray])
    }
    
    // MARK: Requests
    
    
    // MARK: Display logic
    
}

// MARK: Setup Style

extension PortfolioViewController {

    private func setupStyle() {
        
    }

    private func setupGradient(view: UIView, direction: Direction, colors: [UIColor], locations: [NSNumber]? = nil) {
        let gradientLayer = CAGradientLayer()
        gradientLayer.frame = view.frame
        gradientLayer.colors = colors.cgColor
        gradientLayer.locations = locations
        gradientLayer.startPoint = direction.coordinates.startPoint
        gradientLayer.endPoint = direction.coordinates.endPoint
        view.layer.insertSublayer(gradientLayer, at: 0)
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension PortfolioViewController: PortfolioPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}

extension Array where Element == UIColor {

    var cgColor: [CGColor] {
        return map { $0.cgColor }
    }
}
