//
//  PortfolioConfigurator.swift
//  Devlight
//
//  Created by Anderson Oliveira on 08/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension PortfolioInteractor: PortfolioViewControllerOutput, PortfolioRouterDataSource, PortfolioRouterDataDestination {
}

extension PortfolioPresenter: PortfolioInteractorOutput {
}

class PortfolioConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = PortfolioConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: PortfolioViewController) {
        
        let presenter = PortfolioPresenter()
        presenter.output = viewController
        
        let interactor = PortfolioInteractor()
        interactor.output = presenter
        
        let router = PortfolioRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
