//
//  PortfolioInteractor.swift
//  Devlight
//
//  Created by Anderson Oliveira on 08/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol PortfolioInteractorInput {
    
}

protocol PortfolioInteractorOutput {
    
}

protocol PortfolioDataSource {
    
}

protocol PortfolioDataDestination {
    
}

class PortfolioInteractor: PortfolioInteractorInput, PortfolioDataSource, PortfolioDataDestination {
    
    var output: PortfolioInteractorOutput?
    
    // MARK: Business logic
    

}
