//
//  PortfolioPresenter.swift
//  Devlight
//
//  Created by Anderson Oliveira on 08/11/18.
//  Copyright (c) 2018 Anderson Oliveira. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol PortfolioPresenterInput {
    
}

protocol PortfolioPresenterOutput: class {
    
}

class PortfolioPresenter: PortfolioPresenterInput {
    
    weak var output: PortfolioPresenterOutput?
    
    // MARK: Presentation logic
    
}
